version: '3.8'
services:
  nest:
    build:
      context: ./back-project
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - ./back-project:/app
  mysql:
    image: mysql
    env_file:
      - ./back-project/.env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    image: angular-app
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./front-end:/app
volumes:
  mysql-data: